version: "3.9"

services:
  backend:
    build: ./OnlineClothesShop
    ports:
      - "7081:80"
    depends_on:
      - sqlserverdb
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:7081

  sqlserverdb:
    container_name: sqlserverdb
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Lesson123!"
      ACCEPT_EULA: "Y"
  frontend:
    build:
      context: ./OnlineClothesShopFrontend/clothes-shop-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
